version: "3.1"

services:
  redis_container:
    image: redis:7.0.12-alpine
    container_name: my_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf --requirepass yakmukjja103